spring.application.name=Module2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/hp/Desktop/SpringBoot/db
spring.datasource.username=manya
spring.datasource.password=Manya123
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

